greenbone/actions

coverage-js/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add action that tests JS with coverage

coverage-python/action.yaml
**What**:
**Why**:
**How**:
```
usage: codecov [-h] [--version] [--token TOKEN] ...
...
--token TOKEN, -t TOKEN
Private repository token or @filename for file containing the token. 
Defaults to $CODECOV_TOKEN. 
Not required for public repositories on Travis CI, CircleCI and AppVeyor
```
**Checklist**:
=> Add token parameter to codecov action

.github/workflows/test.yml, reference-version/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Fixing the reference branch action

.github/workflows/test-container-image-tags.yml, .github/workflows/test-doc-coverage.yml, .github/workflows/test-release.yml, README.md, coverage-python/action.yaml, release-patch/action.yaml, release/action.yaml
**What**:
Add a new action for releasing with pontos
Example:
```yml
release-patch:
runs-on: ubuntu-latest
name: Test Release Calendar changelog
steps:
- name: Checkout
uses: actions/checkout@v2
- name: Run release patch actions
uses: greenbone/actions/release@v1
with:
github-user: foo
github-user-mail: foo@bar.baz
github-user-token: bar
gpg-key: boo
gpg-passphrase: foo
gpg-fingerprint: baz
conventional-commits: false
strategy: calendar
```
**Why**:
Maintaining in a single place of failure
**How**:
**Checklist**:
=> Add a new action for releasing with pontos

lint-python/action.yaml
**What**:
* Add missing `version` parameter to the lint action
**Why**:
**How**:
**Checklist**:
=> add the version input

.github/workflows/test-release.yml, README.md, release/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add branch input, also implement fetch-depth with CC

.github/workflows/test-release.yml, release-python/action.yaml, release/action.yaml
**What**:
**Why**:
* The original release action fails for python projects
* Easiest fix, so it uses poetry
**How**:
**Checklist**:
=> Create a detached actions to release python projects

release-python/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> python run pontos-version

.github/workflows/release-action.yml
* Add an action that can be triggered after a new action has been added, or a fix has been made on an existing action.
* This action basically runs (by Greenbone Bot):
```
git checkout v1
git tag <input>
git push --tags
git push
```
**What**:
**Why**:
* Simplify releasing new actions
**How**:
**Checklist**:
=> Release Actions

.github/workflows/release-action.yml
**What**:
**Why**:
- Workflow didn't work as expected.
**How**:
**Checklist**:
=> Fix workflow for releasing actions.

.github/workflows/release-action.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Fixing Actions repo release workflow

backport-pull-request/action.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Use corresponding docker image for action

backport-pull-request/action.yml, backport-pull-request/action/backport.py
**What**:
**Why**:
**How**:
**Checklist**:
=> Rebase v1 into main

.github/workflows/test-release.yml
see #26 - add only the missing part for PRs
=> clean-up(release): run only when it is needed - also on PRs

.github/workflows/artifacts-download-trigger-build.yml
**What**:
push dist to repo
**Why**:
see #28
=> build(container-image-tags): push to repo

README.md, update-header/action.yaml
**What**:
new action to update header:
```yaml
- name: Run update header
uses: greenbone/actions/update-header@v1
with:
github-user: ${{ secrets.GREENBONE_BOT }}
github-user-mail: foo@bar.baz
github-user-token: bar
directories: foo tests
target: main
```
**Why**:
**How**:
**Checklist**:
=> Add an action to update headers and create a PR

update-header/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Also add a PR body and improve title

release-python/action.yaml, release/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Remove `--patch` from release arguments, because it is not allowed

release-python/action.yaml
**What**:
fetch-depth can't be -1 it must be 0 or positive 
**Why**:
will make problems
=> fetch-depth can't be -1

.github/workflows/test-hashsums.yml, README.md, hashsums/action.yaml, hashsums/hashsums.sh
**What**:
Add a new hashsums action to create a hashsums file from a directory
DEVOPS-165
**Why**:
We need sha256sums files for the feed deployment.
**How**:
**Checklist**:
=> Add a new hashsums action to create a hashsums file from a directory

hashsums/hashsums.sh
**What**:
Don't fail generating hashsums if there is an empty directory
**Why**:
**How**:
**Checklist**:
=> Fix generating hashsum files

artifacts-download-trigger/dist/index.js, artifacts-download-trigger/src/workflow-handler.ts
**What**:
**Why**:
**How**:
**Checklist**:
=> fix stale filter for workflow_dispatch

artifacts-download-trigger/dist/index.js, artifacts-download-trigger/src/main-dl.ts
**What**:
**Why**:
**How**:
**Checklist**:
=> fix stale filter for workflow_dispatch part 2 downloader

mattermost-notify/action.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Change: use python and reduce inputs

.github/dependabot.yml
**What**: Enabling Dependabot version updates for actions
**Why**:
**How**:
**Checklist**:
=> Init dependabot

artifacts-download-trigger/action.yml
**What**:
Branch seems to be required, otherwise the Workflow can not be found, thus either add `default` (currently added) or use `required: true`
**Why**:
**How**:
**Checklist**:
=> Fix: `branch` seems to be required

.github/workflows/release-action.yml
**What**:
use branch protection for the release.
**Why**:
**How**:
**Checklist**:
=> Make release new versions working again

.github/workflows/release-action.yml
**What**:
To prevent the github default behavior on checkout, we need to checkout with the bot token.
**Why**:
**How**:
**Checklist**:
=> Checkout with Bot Token

.github/dependabot.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: yarn updates in dependabot.yml

mattermost-notify/README.md, mattermost-notify/action.yml
**What**:
Add Mattermost notify highlight support
**Why**:
**How**:
**Checklist**:
=> Add: Mattermost notify highlight support

.github/workflows/test-trigger-workflow-failing-workflow.yml, .github/workflows/test-trigger-workflow-long-running-workflow.yml, .github/workflows/test-trigger-workflow.yml
**What**:
Improve trigger-workflow action tests
**Why**:
Fix the tests
**How**:
**Checklist**:
=> Improve trigger-workflow action tests

.github/workflows/download-artifact-action-container.yml, .github/workflows/test-download-artifacts-test-workflow.yml, .github/workflows/test-download-artifacts.yml, download-artifact/.dockerignore, download-artifact/.pylintrc, download-artifact/Dockerfile, download-artifact/LICENSE, download-artifact/README.md, download-artifact/action.yml, download-artifact/action/artifact.py, download-artifact/poetry.lock, download-artifact/pyproject.toml
**What**:
Add a download-artifact action
**Why**:
In conjunction with the new trigger-workflow action this will replace the artifacts-download-trigger action.
**How**:
**Checklist**:
=> Add a download-artifact action

.github/workflows/download-artifact-action-container.yml, .github/workflows/trigger-workflow-action-container.yml
**What**:
Set correct image names for ghcr.io upload
**Why**:
The container upload workflows are failing currently.
**How**:
**Checklist**:
=> Fix: Set correct image names for ghcr.io upload

download-artifact/README.md
**What**:
Explain in detail how the action finds an artifact which gets downloaded.
**Why**:
The action takes some assumptions which may be no obvious to the user.
**How**:
**Checklist**:
=> Explain how the download-artifact action works internally

trigger-workflow/action.yml
**What**:
Fix name of the trigger workflow action in the yml file
**Why**:
Copy and paste mistake
**How**:
**Checklist**:
=> Fix name of the trigger workflow action in the yml file

download-artifact/action/artifact.py, download-artifact/poetry.lock, download-artifact/pyproject.toml, trigger-workflow/action/trigger.py, trigger-workflow/poetry.lock, trigger-workflow/pyproject.toml
**What**:
The GitHubEnvironment got a is_debug property and WorkflowRunStatus has been added to the GitHub API.
**Why**:
**How**:
**Checklist**:
=> Remove duplicate code by using pontos 22.9.6

download-artifact/README.md, download-artifact/action.yml, download-artifact/action/artifact.py
**What**:
Allow to get the downloaded artifacts and total number of downloaded artifacts. 
**Why**:
Allow to run following jobs conditionally on the downloaded artifacts.
**How**:
**Checklist**:
=> Add: Extend download-artifact with output variables

download-artifact/action/artifact.py
**What**:
Change downloaded artifact owner to 1001 user
**Why**:
Docker based action are running as the root user in the runner. "Normal" actions are run as the standard 1001 user. Therefore to allow changing the downloaded artifact content via "normal" actions change the ownership to the user with ID 1001.
**How**:
**Checklist**:
=> Add: Change downloaded artifact owner to 1001 user

download-artifact/action/artifact.py
**What**:
Handle setting the user more sanely
**Why**:
Don't fail completely if the user can't be looked up.
**How**:
**Checklist**:
=> Change: Handle setting the user more sanely

backport-pull-request/Dockerfile
**What**:
Install git in backport-pull-request action container
**Why**:
Without git the backport action can't work.
**How**:
**Checklist**:
=> Fix: Install git in backport-pull-request action container

mypy-python/action.yaml
**What**:
**Why**:
To introduce mypy into greenbone python repositories
**How**:
Copied and modified the linting-python action and adjust it to run mypy
**Checklist**:
=> Add: mypy-linting-action for python

mypy-python/action.yaml
**What**:
Add mypy-action
**Why**:
To check annotated types in PR
**How**:
run mypy in the repo when a PR is updated
**Checklist**:
- [ x] Tests
- [ x] Conventional comit
=> Add: mypy-action

github-release/README.md, github-release/action.yml
**What**:
Add: github release action
**Why**:
**How**:
**Checklist**:
=> Add: github release action

backport-pull-request/poetry.lock, download-artifact/poetry.lock, trigger-workflow/poetry.lock
**What**:
Update Python dependencies for our Python based Docker actions.
**Why**:
Newest releases especially pontos with the GitHub Actions output change.
**How**:
**Checklist**:
=> Update Python dependencies

poetry/action.yaml
**What**:
update setup-python actions dependency
**Why**:
dependabot is not doing it's job ... :(
**How**:
**Checklist**:
=> Update dependency of setup-python in poetry action

.github/dependabot.yml
**What**:
* Add some github actions dependabot directories so the dependencies get updated
**Why**:
**How**:
**Checklist**:
=> Add some directories to dependabot

.github/dependabot.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add more actions to dependabot

.github/dependabot.yml
**What**:
remove the file names from the dependabot yaml ...
**Why**:
* Dependabot does not work with the explicit files ...
**How**:
**Checklist**:
=> Remove explicit files from dependabot

.github/dependabot.yml, lint-npm/action.yaml, test-npm/action.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Use the correct action

install-npm/action.yaml
**What**:
Fix: Remove the shell value
**Why**:
fix workflow
**How**:
**Checklist**:
=> Fix: Remove the shell value

.github/workflows/release-action.yml
**What**:
- for the actions release action (merge to v2), remove fast-forward only
**Why**:
not required
**How**:
**Checklist**:
=> Change: merge without fast-forward

.github/workflows/release-action.yml
**What**:
* Remove branch-protection stuff
* improve comments, prints
* add merge-commit message
**Why**:
branch-protection stuff never existed working
comments always good
**How**:
**Checklist**:
=> Change: Remove branch-protection stuff, improve comments, add merge-commit message

.github/workflows/release-action.yml
**What**:
Fix: merging the default branch
**Why**:
**How**:
**Checklist**:
=> Fix: merging the default branch

README.md, lint-golang/action.yml
**What**:
* Adding an action for golang linting
* it is basically only using the golangci-lint action, since my initial research classified this as the best practice currently (there are a lot of different linters and this seems to run multiple parallel and is very configurable)
**Why**:
* Easier usage
* Unifying golang linting for greenbone projects
**How**:
* it is basically only using the golangci-lint action
**Checklist**:
=> Add: Action for golang linting

lock-branch/action.yaml
**What**:
Add an action to lock/unlock a branch via branch protection rules.
**Why**:
Allow to lock/unlock PR merges.
=> Add: Lock/unlock branch action

lock-branch/action.yaml
**What**:
- Correct the path to download the script file.
**Why**:
Path was incorrect, -o is also wrong
**How**:
**Checklist**:
=> Fix: Make the wget file paths correct

download-artifact/action/artifact.py, download-artifact/poetry.lock, download-artifact/pyproject.toml, trigger-workflow/action/trigger.py, trigger-workflow/poetry.lock, trigger-workflow/pyproject.toml
**What**:
Use GitHubAsyncRESTApi for running the actions. 
**Why**:
The old sync API will be removed in near future.
=> Change: Refactor trigger-workflow and download-artifact actions

download-artifact/action/artifact.py
**What**:
Improve the download-artifact action.
**Why**:
* Fix error output during downloading an artifact
* Improve speed a bit
* Improve debug log
=> Download Artifact Improvements

README.md, admin-bypass/action.yaml
**What**:
* Adding new action for allowing admins bypassing branch protection
**Why**:
* Branch protection is important, should not be bypassed by admins
**How**:
**Checklist**:
=> Add: New action for allowing admins bypassing branch protection

release-python/action.yaml
**What**:
Improve release python action
**Why**:
It's not necessary to pass the current version to the sign command. Without passing a release version the current version is used automatically in the sign command.
=> Improve release python action

README.md, release-python/action.yaml, release/action.yaml
Adding Locking Feature to release actions, so we can activate the admin bypass branch protection rule
Also formatting release actions
Also fixing indentation in README
so we can activate the admin bypass branch protection rule
DEVOPS-534
=> Add: Bypass Admin feature to the release actions

README.md, release-python/action.yaml, release/action.yaml
Unify release actions
At the end the release action should replace the release-python action. As the first step both actions should be as similar as possible.
=> Change: Unify release actions

backport-pull-request/action/backport.py, backport-pull-request/action/config.py
Try to improve the backport action
Try to get rid of the issue from https://github.com/greenbone/data-objects/actions/runs/4073492530/jobs/7017489259
https://github.com/greenbone/data-objects/actions/runs/4073492530/jobs/7017489259
=> Change: Try to improve the backport action

backport-pull-request/action/backport.py
Another try to fix setting git config for backport action
Use different checkout dir then workspace (maybe some issue with the docker container?) and try writing to git config file directly if `git config` command fails.
=> Change: Another try to fix setting git config for backport action

backport-pull-request/action/backport.py
Use a temporary directory for the git checkout.
Use a stateful git instance to allow changing the checkout directory.
Hopefully fix the backport issues.
DEVOPS-537
=> Change: Use a temporary directory for the git checkout

backport-pull-request/action/backport.py, backport-pull-request/action/config.py, backport-pull-request/poetry.lock, backport-pull-request/pyproject.toml
Next Generation of the backport action that works with rebase and squash merges too.
Get a working backport action for all use cases.
DEVOPS-364
Tested extensively in the pipeline-experiments repo.
=> Backport Action NG

helm-build-push/README.md, helm-build-push/action.yaml
Add: build and push helm chart action
DEVOPS-533
DEVOPS-533
=> Add: build and push helm chart action

helm-build-push/README.md, helm-build-push/action.yaml
Change: Remove defaults in  helm-build-push action
${{ vars.IMAGE_REGISTRY }} env dont work.
None
=> Change: Remove defaults in  helm-build-push action

helm-build-push/action.yaml
[Add: helm dependency update](https://github.com/greenbone/actions/commit/9e6b029f92e473d97a1c2846ce37c2b026d37e68)
If we have dependencies in our charts, they must be downloaded beforehand.
DEVOPS-533
DEVOPS-533
=> Add: helm dependency update

download-artifact/README.md
=> Update Readme: Use v2

README.md
correct readme content
release actions
=> Docs: Update the readme

check-version/action.yaml, release/action.yaml
Some small improvements
Consistency
=> Small improvements

README.md, release/REAMDE.md, release/action.yaml
add more release options
We added these features to pontos and want to use this to make the release action more powerful
DEVOPS-584
=> Change: Add major, minor, pre-release options to action

release/action.yaml
Fix release signing
https://github.com/greenbone/pontos/pull/645
=> Fix: Remove release-version argument from sign

download-artifact/action/artifact.py, download-artifact/poetry.lock, download-artifact/pyproject.toml
change version
add http status to error message
* Fix 415 Unsupported Media Type, see https://github.com/greenbone/pontos/pull/649
=> Force `pontos` version to 23.3.0

helm-build-push/README.md, helm-build-push/action.yaml
Change: Make input arguments small
Most other input arguments are small.
None
=> Change: Make input arguments small

install-node/action.yaml, lint-node/action.yaml, test-node/action.yaml
Fix: Node actions if conditions
They were broken and the conditions don't require the curly brackets
=> Fix: Node actions if conditions

test-node/action.yaml
=> Fix: Node actions if conditions(4)

release/action.yaml
Fix usage of set-github-user action
Fix explicit version setting
* Action is faulty
=> Fix: Release action

README.md, backport-pull-request/action/__init__.py, backport-pull-request/action/backport.py, backport-pull-request/action/config.py, backport-pull-request/tests/__init__.py, backport-pull-request/tests/test_config.py, docker-run/LICENSE, download-artifact/action/artifact.py, helm-version-upgrade/action/helm_chart_version_upgrade.py, trigger-workflow/action/trigger.py
Used `LC_ALL=C  find ./ -type f -exec sed -i '' -e 's/Greenbone Networks GmbH/Greenbone AG/g' {} \;` (Mac!)
We are AG now
=> Reorganize `Greenbone AG`

release/README.md, release/action.yaml
add input for versioning scheme
Switch between pep440 and semantic versioning
DEVOPS-598
=> Change: Add versioning-scheme argument

release/README.md, release/action.yaml
semver not semantic
was incorrect
DEVOPS-598
=> Fix: Use correct semver input name

helm-build-push/action.yaml
Improvement Ideas for helm-chart build-push action
I think it is more easy to use this action like this?
DEVOPS-577
=> Refactor: Helm-Chart build-push action

helm-version-upgrade/README.md, helm-version-upgrade/action.yml, helm-version-upgrade/action/helm_chart_version_upgrade.py
Add: dependencies upgrade support to helm_chart_version_upgrade
We need to update dependencies in helm charts.
DEVOPS-576
=> Add: dependencies upgrade support to helm_chart_version_upgrade

admin-bypass/action.yaml, coverage-python/action.yaml, lint-python/action.yaml, mypy-python/action.yaml, trigger-workflow/action.yml, update-header/action.yaml
Allow to set poetry version
When using poetry to install python packages allow to use a specific poetry version.
=> Change: Allow to set poetry version

helm-version-upgrade/action.yml, poetry/action.yaml, trigger-workflow/action.yml
Allow to set a path to the lockfiles for the poetry caching
Should fix caching issues when poetry is used within a composite action.
=> Fix: Allow to set a path to the lockfiles for the poetry caching

coverage-python/action.yaml, lint-python/action.yaml, mypy-python/action.yaml, poetry/action.yaml
Improve poetry action
* Change cache input variable into a flag
* Better output for installed poetry and pip version information
* Don't fail installing poetry with enabled caching on our self hosted runners
Forward caching inputs to poetry action 
Cleaner and better code
=> Improve poetry action

dependency-review/action.yml
Add Unlicense license to allowed licenses
Allowed to use, currently also required
=> Add Unlicense

conventional-commits/action/commits.py
Improve conventional commits report
Fix formatting of the PR comment message.
DEVOPS-602
=> Improve conventional commits report

.github/workflows/test-python.yml, poetry/action.yaml
Allow to cache the poetry installation
Speed up the installation of poetry when using the poetry action by implementing caching.
=> Add: Allow to cache the poetry installation

sbom-upload/README.md
Cosmetic change, remove spaces in the READ.md file.
OCD
Related to Jira [DEVOPS-622](https://jira.greenbone.net/browse/DEVOPS-622)
More info [spdx-dependency-submission-action](https://github.com/marketplace/actions/spdx-dependency-submission-action)
=> Fix space issue

sbom-upload/action.yml
Added double quote to the company name Greenbone AG
Shell script the right way
=> Added double quote to the company name

admin-bypass/action.yaml, backport-pull-request/action.yml, check-version/action.yaml, download-artifact/action.yml, lock-branch/action.yaml, mattermost-notify/action.yml, release/action.yaml, update-header/action.yaml
Allow to cache all python environments
Improve running Python code in composite actions via virtual environments. Define the path of the environment in a central step and cache the environments for faster installations.
=> Add: Allow to cache all python environments

sbom-upload/action.yml
=> Fix: Running command in `bash` shell

dependency-review/action.yml
Fix Scheme of license
Previous version was not SPDX compliant
=> Fix: License Check

check-version/action.yaml
Improve check-version action
* Checkout the git repository by default
* Allow to set desired Python version
* Make working directory configurable
More flexible and easier to use action
=> Change: Improve check-version action

dependency-review/action.yml
Added license ISC
It is in the permitted licenses
=> Added license ISC

conventional-commits/README.md
Update README of conventional commits action
An argument was missing and token is optional.
=> Change: Update README of conventional commits action

release/action.yaml
=> Fix release action

.github/workflows/conventional-commits.yml
Set pull-request write permissions on conventional commits action
Add necessary permissions for the workflow.
=> Change: Set pull-request write permissions on conventional commits action

conventional-commits/README.md
Add required permissions to conventional commits readme example
State which permissions are required to run the action.
=> Add: Add required permissions to conventional commits readme example

release/README.md, release/action.yaml, setup-pontos/README.md, sign-release-files/README.md, sign-release-files/action.yml
Update and fix READMEs
Document the code. Improve READMEs for release, sign-release-files and setup-pontos actions.
=> Change: Update and fix READMEs

README.md, admin-bypass/README.md, backport-pull-request/README.md, check-version/README.md, conventional-commits/README.md, coverage-python/README.md, download-artifact/README.md, lint-python/README.md, lock-branch/README.md, lock-branch/action.yaml, mattermost-notify/README.md, poetry/README.md, poetry/action.yaml, pypi-upload/README.md, release/README.md, setup-pontos/README.md, sign-release-files/README.md, trigger-workflow/README.md
Update documentation for actions
Update and improve README for documenting the actions.
=> Change: Update documentation for actions

release/action.yaml, sign-release-files/action.yml
Fix some issues within the release action
It wasn't possible to sign release assets.
https://github.com/greenbone/actions/actions/runs/4956354993/jobs/8866700384
=> Fix release bugs

backport-pull-request/.pylintrc, backport-pull-request/README.md, backport-pull-request/action.yml
Improve backport action
Fix some glitches. Especially document the required permissions.
=> Improve backport action

checkout/README.md, checkout/action.yml
Add an extended checkout action
Provide an extended checkout action to allow getting information about the checked out git repository.
=> Add: Add an extended checkout action

dependency-review/action.yml
Add: Allow GPL-3.0-or-later AND LGPL-3.0 AND LGPL-3.0-only
GitHub reports GPL-3.0-or-later AND LGPL-3.0 AND LGPL-3.0-only for the platformdirs Python package
=> Add: Allow GPL-3.0-or-later AND LGPL-3.0 AND LGPL-3.0-only

dependency-review/action.yml
=> Fix: missing comma

dependency-review/action.yml
Add CC-BY-4.0 to list of allowed licenses
Dependency review failed for styled-components in greenbone/scan-management-frontend
https://github.com/greenbone/scan-management-frontend/actions/runs/5444659395/jobs/9902812097?pr=746
- [N/A] Tests
=> Add: Add CC-BY-4.0 to list of allowed licenses

lint-python/README.md, lint-python/action.yaml
Support different Python linter
Allow to run tests with ruff at the end.
=> Change: Support different Python linter

container-build-push-3rd-gen/README.md, container-build-push-3rd-gen/action.yaml, container-build-push-docker/README.md, container-build-push-docker/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml, container-build-push-ghcr/README.md, container-build-push-ghcr/action.yaml
Add: container-build-push actions
DEVOPS-729
DEVOPS-729
=> Add: container-build-push actions

helm-build-push/README.md, helm-build-push/action.yaml
Add: tag and digest output to helm build and push action
Add: gpg-secret-key support
Add gpg secret key to support  helm verify.
DEVOPS-730
=> Add: gpg-secret-key support to helm build and push

helm-build-push/README.md
=> Fix: README.md typo

release/README.md, release/action.yaml, sign-release-files/README.md, sign-release-files/action.yml
Add git-tag-prefix input to adjust that prefix if needed
Needed for e.g cloud repos
DEVOPS-733
=> Add: git-tag-prefix input to adjust that prefix if needed

conventional-commits/action/commits.py
Improve error message for failing conventional commits action
Allow for better debugging the cause of the failed action.
=> Improve error message for failing conventional commits action

dependency-review/action.yml
Add: Allow `MIT/Apache-2.0` and `(MIT OR Apache-2.0) AND Unicode-DFS-2016`
GitHub reports this licenses as invalid for Rust packages (openvas/rust)
=> Add: Allow MIT/Apache-2.0, and (MIT OR Apache-2.0) AND Unicode-DFS-2016

container-build-push-3rd-gen/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml
Add: input value cosign-tlog-upload in container-build-push-generic
Add: cosign-tlog-upload = false to container-build-push-3rd-gen
DEVOPS-736
DEVOPS-736
=> Add: cosign-tlog-upload = false to container-build-push-3rd-gen

helm-build-push/README.md, helm-build-push/action.yaml
Add: input value gpg-secret-key-password
DEVOPS-737
DEVOPS-737
=> Add: input value gpg-secret-key-password

container-signing/README.md, container-signing/action.yaml
Add: cosign-tlog-upload input value for container-signing action
DEVOPS-736
DEVOPS-736
=> Add: cosign-tlog-upload input value for container-signing action

container-build-push-generic/action.yaml
Remove: checkout action
The checkout action should not be in an action.
None
=> Remove: checkout action

.github/workflows/release-action.yml, release/README.md, release/action.yaml
Fix current release workflow
At the moment the release action requires a ref
=> Fix release

mypy-python/README.md
Add README for mypy-python action
The readme was missing
=> Add: Add README for mypy-python action

release/action.yaml
Use our v3 actions in the release action
Now we have a v3 version we can use the v3 actions in the release action too.
=> Use our v3 actions in the release action

.github/workflows/test-python.yml
Add a test for running the pipx action
Ensure that the pipx action runs as expected.
DEVOPS-763
=> Add a test for running the pipx action

mattermost-notify/README.md, mattermost-notify/action.yml
Use pipx for installation and add additional inputs
Faster installation of the action and more flexibility.
DEVOPS-763
DEVOPS-722
Requires self hosted runner having pipx installed.
=> Refactor mattermost notify action

mattermost-notify/action.yml
Fix passing arguments to mattermost notify
Don't override arguments when highlight is used. Instead append the highlight arguments.
=> Fix passing arguments to mattermost notify

container-build-push-3rd-gen/README.md, container-build-push-3rd-gen/action.yaml, container-build-push-docker/README.md, container-build-push-docker/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml, container-build-push-ghcr/README.md, container-build-push-ghcr/action.yaml
Add: Container digest output in action container-build-push
DEVOPS-773
DEVOPS-773
=> Add: Container digest output in action container-build-push

mattermost-notify/action.yml
Fix: command line generation
I hope the command line generation works now this way
None
=> Fix: command line generation

mattermost-notify/README.md, mattermost-notify/action.yml
Add: status input value
For usage with job needs in the same workflow, we need to pass the jobs status from the previous job.
DEVOPS-722
=> Add: status input value

dependency-review/action.yml
Add the following licenses to be allowed:
* BSD-3-Clause AND BSD-3-Clause-Clear
* CC0-1.0
https://github.com/greenbone/gsa/actions/runs/5786039610
=> Allow additional licenses

mattermost-notify/README.md, mattermost-notify/action.yml
Change: Skip mn-notify installation on selected runner
DEVOPS-789
DEVOPS-789
=> Change: Skip mn-notify installation on selected runner

sbom-upload/README.md, sbom-upload/action.yml
Add: commit sbom into repository
DOS-124
DOS-124
Done in pipeline-experiments
=> Add: commit sbom into repository

.github/dependabot.yml
Change: Add grouping to Dependabot
For gods sake ...
DEVOPS-804
=> Change: Add grouping to Dependabot

.github/dependabot.yml
=> Fix fix Dependabot

.github/dependabot.yml
Fix the fix of the fix for DEVOPS-804
=> Fix: Fix: Fix: dependabot.yml

container-build-push-generic/action.yaml
Change: always login into docker reg
In some PR's we need a login to fetch other docker images.
None
=> Change: always login into docker reg

.github/workflows/auto-merge.yml
Auto-merge workflow that activates squash merge on open PRs
Save Dev Time
DEVOPS-804
=> Add: Auto-merge workflow that activates squash merge on open PRs

helm-version-upgrade/README.md, helm-version-upgrade/action.yml, helm-version-upgrade/action/helm_chart_version_upgrade.py
Add: option chart-version-increase into helm-version-upgrade
Add: option for overwrite parent key image tag
DEVOPS-774
DEVOPS-815
DEVOPS-774
DEVOPS-815
=> Add: option chart-version-increase into helm-version-upgrade

helm-version-upgrade/action/helm_chart_version_upgrade.py, helm-version-upgrade/tests/__init__.py, helm-version-upgrade/tests/test_helm_chart_version_upgrade.py
Change: Some cleanup in helm chart version upgrade
Add: some unit tests
Make some code parts easier.
None
=> Change: Some cleanup in helm chart version upgrade

container-build-push-3rd-gen/README.md, container-build-push-3rd-gen/action.yaml, container-build-push-docker/README.md, container-build-push-docker/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml, container-build-push-ghcr/README.md, container-build-push-ghcr/action.yaml
Add: support for build secrets in container related workflows
DEVOPS-821
DEVOPS-821
=> Add: support for build secrets in container related workflows

.github/workflows/release.yml
Change: Update and rename release-action.yml to release.yml
Nameing convention described in DEVOPS-811
DEVOPS-811
=> Change: Update and rename release-action.yml to release.yml

container-build-push-3rd-gen/README.md, container-build-push-3rd-gen/action.yaml, container-build-push-docker/README.md, container-build-push-docker/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml, container-build-push-ghcr/README.md, container-build-push-ghcr/action.yaml
Add: docker scout action into container workflows
DEVOPS-830
DEVOPS-830
=> Add: docker scout action into container workflows

container-build-push-generic/action.yaml
Change: only enable load feature if pull is not set
They can not work to gather.
None
=> Change: only enable load feature if pull is not set

container-build-push-3rd-gen/README.md, container-build-push-3rd-gen/action.yaml, container-build-push-docker/README.md, container-build-push-docker/action.yaml, container-build-push-generic/README.md, container-build-push-generic/action.yaml, container-build-push-ghcr/README.md, container-build-push-ghcr/action.yaml
Add: sarif-retention-days option
Don't want to store the artifact forever.
None
=> Add: sarif-retention-days option into container related workflows

container-build-push-generic/README.md, container-build-push-generic/action.yaml
Add: input arguments for scout-keep-previous-comments
We want to have this docker scout PR comments optional.
None
=> Add: input argument for scout-keep-previous-comments

dependency-review/action.yml
Add: BlueOak-1.0.0 license to permitted list
Request by Scan Control
LEG-122
=> Add: BlueOak-1.0.0 license to permitted list

ssh-run-cmd/action.yaml
Add possibility to pass a shell script via SSH ...
Sometimes execution gets really complex, using a file instead of a lot of commands can be more easy ...
=> Add: possibility to pass a shell script via SSH

helm-build-push/README.md, helm-build-push/action.yaml
Added Validate Helm Chart to helm build push
[DEVOPS-892](https://jira.greenbone.net/browse/DEVOPS-892)
[DEVOPS-892](https://jira.greenbone.net/browse/DEVOPS-892)
=> Added Validate Helm Chart to helm build push

set-github-user/README.md, set-github-user/action.yaml
adding optional working directory
when setting the remote URL, it must be important to also set the remote URL in the correct directoryy
=> Add: Working directory to `set-github-user` action

mypy-python/README.md, mypy-python/action.yaml
Working Directory to MyPy Action
set working directory, when I need it ... align with other python actions ...
DEVOPS-950
=> Add: Working Directory to MyPy Action

mypy-python/action.yaml
=> Fix: MyPy Working Directory

container-build-push-generic/action.yaml
Fix: input value image-url handling in container-build-push-generic action
DEVOPS-884
DEVOPS-884
=> Fix: input value image-url handling in 

helm-login/README.md, helm-login/action.yaml
Add: helm login
We may want a separate action to log in to an OCI registry and install a specific Helm version that does not correspond to the one pre-installed on the runners.
DEVOPS-977
Tested in pipeline-experiments
=> Add: helm login

container-build-push-generic/action.yaml
Change: update docker actions
We need the v5 action for annotations
None
=> Change: update docker actions

container-build-push-generic/README.md, container-build-push-generic/action.yaml
Add: setup-qemu
Add: inputs.scout-command
Add: inputs.meta-annotations-levels
We need qemu to build arm64 images and to set the cout-command and meta-annotations-levels dynamic is nice to have.
None
=> Add: setup-qemu, inputs.scout-command, inputs.meta-annotations-levels

pipx/README.md, pipx/action.yml
Add: pipx --include-deps install option
Some application installations with pipx need this option, to install all program binaries.
None
=> Add: pipx --include-deps install option

awx-run/README.md, awx-run/action.yml, awx-run/run-awx-job.yml, awx-run/run-awx-project.yml, awx-run/run-awx-workflow.yml
Add: AWX job action
This enables us to initiate jobs and workflows on an AWX server, as well as update a project within AWX.
DEVOPS-978
Tested in pipeline-experiments.
=> Add: AWX job action

scp/README.md, scp/action.yaml
Add: scp action
Sometimes we need to pull/push files from other systems.
DEVOPS-993
Tested in pipeline-experiments.
=> Add: scp action

.github/workflows/dependency-review.yml, dependency-review/action.yml
Add PR comment
Remove failing NOASSERTION license ...
Fix the action, which contains a currently failing license
=> Change: Dependency Review.

npm-build-push/README.md, npm-build-push/action.yaml
Add: init npm-build-push
DEVOPS-612
DEVOPS-612
Not tested yet.
=> Add: init npm-build-push

container-build-push-generic/action.yaml
Change: container-build-push-generic scout action to v1
DOS-249
DOS-249
=> Change: container-build-push-generic scout action to v1

container-build-push-generic/action.yaml, container-signing/README.md, conventional-commits/action.yml, doc-coverage-clang/action.yml, helm-login/action.yaml, lint-golang/action.yml, npm-build-push/README.md, npm-build-push/action.yaml, pr-conventional-commit-labeler/action.yml, sbom-upload/action.yml, update-header/action.yaml
The versions of the used actions need to be updated manually 
Within our actions, the used actions are outdated, because dependabot is not updating them properly
[DEVOPS-1067](https://jira.greenbone.net/browse/DEVOPS-1067)
=> Deps: update the version of the used actions

container-multi-arch-manifest/README.md, container-multi-arch-manifest/action.yaml
Add: container-multi-arch-manifest action
DEVOPS-1082
DEVOPS-1082
=> Add: container-multi-arch-manifest action

dependency-review/action.yml
Dependency-review action missing comma
action fails in workflows
#1197
=> Fix: Dependency-review action missing comma

container-multi-arch-manifest/action.yaml
Add: Print digest and tags output manifest action
Add print output of tags and digest for information and debug.
DEVOPS-1135
=> Add: Print digest and tags output manifest action

container-multi-arch-manifest/action.yaml
Add: sort digest in manifest action
With more then on tag passt to the manifest command it outputs more then on time the digest so we have to sort it.
None
=> Add: sort digest in manifest action

container-multi-arch-manifest/action.yaml
Fix: multi line output in manifest action
Multi line is a special thing in github actions....
None
=> Fix: multi line output in manifest action

update-header/action.yaml
=> extend license header action with license type input

oci-info/action/oci.py, oci-info/action/oci_model.py
Add: more debug output to ociinfo
Some repository's don't habe manifests to lets raise an error for it.
DEVOPS-1150
=> Add: more debug output to ociinfo

container-build-push-generic/README.md, container-build-push-generic/action.yaml
Add: flavor input support for container-build-push-generic
Some workflows need to set an other tag behavior.
None
=> Add: flavor input support for container-build-push-generic

container-multi-arch-manifest/README.md, container-multi-arch-manifest/action.yaml
Add: support for meta action tag list
Sometimes we want to use the tag list from docker's meta action.
DEVOPS-1223
=> Add: support for meta action tag list

is-latest-tag/action.yml
=> Add: Echo if latest tag or not.

.github/dependabot.yml
and use https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
less code ...
=> Add: them all

.github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/test-doc-coverage.yml, .github/workflows/test-download-artifacts-test-workflow.yml, .github/workflows/test-download-artifacts.yml, .github/workflows/test-hashsums.yml, .github/workflows/test-is-latest-tag.yml, .github/workflows/test-python.yml, .github/workflows/test-signature.yml, .github/workflows/test-trigger-workflow.yml, .github/workflows/unittests.yml
Changed the vX notation for actions to the actual hashcode.
The actions become immutable this way. Dependabot can update the hashcode to the last released version on it's own.
DEVOPS-1310
=> Change: Versions immutable through hashcode

container-multi-arch-manifest/README.md, container-multi-arch-manifest/action.yaml
Add: exit code check in container-multi-arch-manifest
It missed this step last time.
None
=> Add: exit code check in container-multi-arch-manifest

container-multi-arch-manifest/action.yaml
Add: missing outputs to container-multi-arch-manifest
The outputs declaration is missing.
None
=> Add: missing outputs to container-multi-arch-manifest

admin-bypass/action.yaml, awx-run/action.yml, backport-pull-request/action.yml, check-version/action.yaml, container-build-push-generic/action.yaml, container-multi-arch-manifest/action.yaml, conventional-commits/action.yml, coverage-python/action.yaml, download-artifact/action.yml, helm-version-upgrade/action.yml, lint-node/action.yaml, lint-python/action.yaml, lock-branch/action.yaml, mattermost-notify/action.yml, mypy-python/action.yaml, oci-info/action.yml, poetry/action.yaml, pr-conventional-commit-labeler/action.yml, release/action.yaml, sbom-upload/action.yml, scp/action.yaml, setup-pontos/action.yml, sign-release-files/action.yml, ssh-run-cmd/action.yaml, test-node/action.yaml, trigger-workflow/action.yml, update-header/action.yaml
Update greenbone actions in composite actions
they are outdated
=> Deps: Update greenbone actions in composite actions

admin-bypass/action.yaml, awx-run/action.yml, backport-pull-request/action.yml, check-version/action.yaml, container-build-push-generic/action.yaml, container-multi-arch-manifest/action.yaml, conventional-commits/action.yml, coverage-python/action.yaml, download-artifact/action.yml, helm-version-upgrade/action.yml, lint-node/action.yaml, lint-python/action.yaml, lock-branch/action.yaml, mattermost-notify/action.yml, mypy-python/action.yaml, oci-info/action.yml, poetry/action.yaml, pr-conventional-commit-labeler/action.yml, release/action.yaml, sbom-upload/action.yml, scp/action.yaml, setup-pontos/action.yml, sign-release-files/action.yml, ssh-run-cmd/action.yaml, test-node/action.yaml, trigger-workflow/action.yml, update-header/action.yaml
Unpin greenbone actions 
we trust them, and otherwise we are in a loop so these actions are never uptodate ...!
=> Deps: Unpin greenbone actions (we trust them)

backport-pull-request/README.md, backport-pull-request/action.yml, conventional-commits/README.md, coverage-python/README.md, coverage-python/action.yaml, download-artifact/action.yml, helm-version-upgrade/action.yml, lint-python/README.md, lint-python/action.yaml, mypy-python/README.md, mypy-python/action.yaml, oci-info/README.md, oci-info/action.yml, poetry/README.md, pr-conventional-commit-labeler/README.md, pr-conventional-commit-labeler/action.yml, trigger-workflow/action.yml
pin poetry version to 1.8.0
Make all actions work again
DEVOPS-1374 DEVOPS-1372
https://github.com/python-poetry/poetry/issues/9961
=> Deps: (Temp) pin poetry version to 1.8.0

pipx/action.yml
Deps: Update actions/cache to 4.2.0
deprecation warning
=> Deps: Update actions/cache to 4.2.0

dependency-review/action.yml
Add zlib to list of allowed licenses in dependency-review action.
The license is allowed and we want to use it.
=> Add: Add zlib to list of allowed licenses in dependency-review action

container-build-push-generic/README.md
Update README for generic container build/push for ARM
Make the relevance of architecture of runner more clear!
=> Change: Update README for generic container build/push for ARM

push-and-sign-artifact/README.md, push-and-sign-artifact/action.yaml
Move the pushing and signing of artifacts into our seperate greenbone action collection.
Reusable code
https://jira.greenbone.net/browse/DEVOPS-1486
=> Add: push and sign an artifact Action

container-build-push-generic/README.md
Docs: Improve README for docker-build-push-generic
🤷🏿
=> Docs: Improve README for docker-build-push-generic

deploy-env/run.yml
Fix: task name in deploy-env/run.yml
None
=> Fix: task name in deploy-env/run.yml

deploy-env/README.md, deploy-env/action.yml, deploy-env/run.yml
Add: multi folder copy and inventory as comma-separated list support
DEVOPS-1237
https://github.com/greenbone/pipeline-experiments/actions/runs/15113368149/job/42480969521
=> Add: multi folder copy and inventory as comma-separated list support in deploy env action

.github/workflows/codeql.yml
Remove erroneous variable from codeql workflow
Matrix isn't available at that point and cannot be used, otherwise workflow doesn't run because it's broken.
We missed that in the change before because the workflow didn't fail but did fail to run and the latter doesn't lead to a problem in merging the PR.
We then still have the problem that CodeQL was failing, which was hidden by the workflow being invalid and not even starting, but a later version was working, so debugging the two years old version is pointless. 
So it's also updated to the next working version.
- [NA] Tests
=> CI: remove erroneous variable from codeql workflow

.github/dependabot.yml
Disable all python stuff and also the directories setting for the github actions job to check if that lets the job run.
Because we are tracking down an unclear error that makes dependabot runs fail.
DEVOPS-1551
- [ NA] Tests
=> CI: Dependabot debugging.

.github/dependabot.yml
Try defining one single directory.
- [NA] Tests
=> CI: dependabot debug - define one directory.

.github/dependabot.yml
dependabot - re-enable python checks
Debugging / fixing in process.
Now that things work again, we activate python to see if it keeps working or if the python stuff triggers the pre-existing failure.
=> CI: dependabot - re-enable python checks

.github/dependabot.yml
dependabot debug - add single directory
Add a single directory of an action that uses an outdated action dependency to check if that works.
=> CI: dependabot debug - add single directory

.github/dependabot.yml
dependabot debug - add all via wildcard
Check if adding all actions via wildcard works.
=> CI: dependabot debug - add all via wildcard

.github/dependabot.yml
dependabot debug - fix overlap
The previously tried wildcard seems to overlap with the other config for /.
Let's see if using the wildcard only gets us updated for the workflows dir of the repository and all actions stored in trhe repository, too.
=> CI: dependabot debug - fix overlap

.github/dependabot.yml
=> CI: dependabot debug

.github/dependabot.yml
dependabot debug - only / and helm-login
=> CI: dependabot debug - only / and helm-login

.github/dependabot.yml
dependabot-debug - remove nonexisting dir
A directory that was only locally available made it in the list of action dirs to check. Removing it.
=> CI dependabot-debug - remove nonexisting dir

container-build-push-generic/action.yaml
Change: Disable the sbom action
The sbom action causes too many problems on our self-hosted runners.
DEVOPS-1685
=> Change: The sbom action causes too many problems on our self-hosted runners

sign-win-binary/README.md, sign-win-binary/action.yml
=> Test branch actions

release-type/action.yml
Add: hotfix to patch release translation in release-type
DEVOPS-1590
DEVOPS-1590
=> Add: hotfix to patch release translation in release-type

sign-win-binary/README.md
=> Fix: Update README.md of sign-win-binary action
