coverage-python/action.yaml

**What**:
GitHub supports to reference other actions in composite actions now.
Therefore switch to use codecov.io upload action instead of using the
deprecated python script.
**Why**:
Action composition is now possible and codecov python tool is deprecated.
**How**:
**Checklist**:

Implement uploading to codecov.io via external action

---

.github/workflows/container.yml
.github/workflows/test-container-image-tags.yml
.github/workflows/test-doc-coverage.yml
.github/workflows/test-python.yml
.github/workflows/test-release.yml
.gitignore

**What**:
This changes the that the action only run if it is needed. So the source is changed related to this workflow.
**Why**:
It should be prevented that not needed workflows are triggered if they have to do with the actual commit/push/pullrequest.
**How**:
**Checklist**:

[Workflows]: clean up - run only if changes related

---

.github/workflows/artifacts-download-trigger-build.yml

**What**:
Build the artifacts-download-trigger action and commit the dist/index.js to the repo.
**Why**:
Sometimes we miss the build, after we made some changes on the source. 
**How**:
**Checklist**:

build(artifacts-download-trigger): commit the build of the distribution file

---

.github/workflows/test-container-image-tags.yml

**What**:
Add a build process that will be triggered and commit the dist of the container-image-tags action.
**Why**:
Sometimes we miss to build the source for the release, this will now automatically done and commit to the repo 
**Checklist**:

build(container-image-tags): commit the build of the distribution file

---

.github/workflows/artifacts-download-trigger-build.yml
.github/workflows/container-images-tags-build.yml
.github/workflows/test-container-image-tags.yml

build dist files only on branches except the main branch and if it is not a pull_request
**What**:
Allow build dist files only on branches except the main branch and if it is not a pull_request.
**Why**:
With this change we get the the dist build done automatically done, while development and when release to v1 branches.

build(*): build dist files logic

---

artifacts-download-trigger/action.yml
artifacts-download-trigger/dist/index.js
artifacts-download-trigger/src/index.ts
artifacts-download-trigger/src/utils.ts

**What**:
Add a feature 'download-artifacts-no-trigger' any workflow
**Why**:
sometimes, you should only download, and not trigger the workflow again you run just run.

Add a feature 'download-artifacts-no-trigger' any workflow

---

download-artifact/action/artifact.py

**What**:
Don't raise error if the first workflows request fails with 404 and allow not found is set.
**Why**:
We want to be able to ignore not found workflows
**How**:
**Checklist**:

Fix: Allow to ignore not found workflow

---

download-artifact/action/artifact.py

**What**:
When running in Docker all code is run a the root user. The workflows are run with a normal system user. Therefore in a workflow it is not possible to write to the created download directory or even move the downloaded artifact. With this change the group and other users are gaining write permissions on all created directories and files.
**Why**:
Allow "normal" workflow commands change the downloaded content.
**How**:
**Checklist**:

Change: Allow other users change the downloaded artifact

---

download-artifact/README.md
download-artifact/action.yml
download-artifact/action/artifact.py

**What**:
Make changing to owner of the downloaded artifacts optional
**Why**:
It seems the default user id is not always 1001 on the runners. Therefore to fix the permission issue we need to set the desired user id via an input variable.
**How**:
**Checklist**:

Change: Make changing to owner of the downloaded artifacts optional

---

download-artifact/README.md
download-artifact/action.yml
download-artifact/action/artifact.py

**What**:
Default to the current repository for the input variable of the download artifact action.
**Why**:
Less required input arguments when used in the current repo.
**How**:
**Checklist**:

Change: Repository for download artifacts defaults to current one now

---

download-artifact/README.md
download-artifact/action.yml
download-artifact/action/artifact.py

**What**:
Allow to change group owner for downloaded artifacts
**Why**:
To fix issues with permissions while using xz it must be possible to adjust the group owner of the downloaded artifacts.
**How**:
**Checklist**:

Add: Allow to change group owner for downloaded artifacts

---

trigger-workflow/action/trigger.py

**What**:
Allow opening the URL from the workflow run console output
**Why**:
Remove dot at the end of the URL. Otherwise the dot is considered as part of the URL.
**How**:
**Checklist**:

Fix: Allow opening the URL from the workflow run console output

---

.github/workflows/test-download-artifacts.yml
.github/workflows/test-trigger-workflow.yml

**What**:
Use GITHUB_BOT_TOKEN for testing trigger and download actions
**Why**:
The user of the github token might not have access permissions (like dependabot) for triggering, uploading and downloading artifacts for the tests. Therefore use a token with sufficient permissions.
**How**:
**Checklist**:

Change: Use GITHUB_BOT_TOKEN for testing trigger and download actions

---

mypy-python/action.yaml

**What**:
Mypy no longer runs in base repo directionary, but rather in specified subfolder given in workflow variable "packages"
**Why**:
To fix a mypy error in which the same sourcefile is found in different module names
**How**:
Changed the folder in which mypy will run
**Checklist**:
- [X ] Conventional Commit

mypy runs only in specified folder

---

download-artifact/README.md
download-artifact/action.yml
download-artifact/action/artifact.py

**What**:
Allow to specify events for considered workflows runs to download artifacts.
DEVOPS-466
**Why**:
Before this change only workflow runs that have been triggered by schedules or workflow dispatch events were considered for downloading an artifact. With this change it is possible to configure the desired events via an input variable. If all events should be considered the workflow-events input variable can be set to and empty string.

Change: Allow to specify workflow run events for to be downloaded artifacts

---

download-artifact/action/artifact.py
trigger-workflow/action/trigger.py

**What**:
Fix running the trigger and download actions
**Why**:
When using the CLI commands generated by poetry these commands are calling a function. Therefore these functions must run the asyncio loop and can't be async.

Fix: Fix running the trigger and download actions

---

download-artifact/action/artifact.py

**What**:
Fix download-artifact action to write binary data to the download file. 
**Why**:
The code expected str before.

Fix: Fix writing binary data to the download file

---

download-artifact/poetry.lock
download-artifact/pyproject.toml
trigger-workflow/poetry.lock
trigger-workflow/pyproject.toml

**What**:
Require latest pontos version for workflow run model parsing
**Why**:
Don't crash actions if a workflow run contains pull request data.

Fix: Require latest pontos version for workflow run model parsing

---

download-artifact/action/artifact.py

**What**:
Don't set encoding if binary file is written
**Why**:
Fix for
> ValueError: binary mode doesn't take an encoding argument

Fix: Don't set encoding if binary file is written

---

download-artifact/action/artifact.py

**What**:
Ensure content is written to disk before reading it as a zip file.
**Why**:
Downloaded file isn't a zip file at the moment.

Fix: Try to fix loading the downloaded content as zip file

---

release-python/action.yaml

**What**:
Fix release python action by reverting daab64585a359182a0ce96b34d948204683c2a54
**Why**:
It's required to set a release version because after the actual release the version will be incremented to a `.dev` version

Fix release python action

---

release-python/action.yaml

Try to fix CI error
Try to fix an error while putting the version into the environment. Error was:
> Errorr Unable to process file command 'env' successfully.
> Error: Invalid format 'x.y.z'.
https://github.com/greenbone/greenbone-feed-sync/actions/runs/4023416442/jobs/6914261613

Try to fix CI error

---

release-python/action.yaml
release/action.yaml

Fix setting the VERSION GitHub environment variable
Setting a GitHub environment variable must use the "name=value" syntax.

Fix: Fix setting the VERSION GitHub environment variable

---

backport-pull-request/action.yml
backport-pull-request/action/backport.py
backport-pull-request/action/config.py

Improve backport action
Allow to set a GitHub username as author for the backported commits and try to fix https://github.com/greenbone/data-objects/actions/runs/4072276664/jobs/7014863203
DEVOPS-365
DEVOPS-537

Improve backport action

---

release-python/action.yaml

Fix putting the VERSION into the GitHub environemnt for release-python action
Again the VERSION is not set correctly.
https://github.com/greenbone/pontos/actions/runs/4072556604/jobs/7015447231

Fix: Fix putting the VERSION into the GitHub environemnt for release-python action

---

backport-pull-request/action.yml

Don't use github variables in action descriptions
Don't use github variables in action descriptions
https://github.com/greenbone/data-objects/actions/runs/4073269591/jobs/7016995658

Fix: Don't use github variables in action descriptions

---

backport-pull-request/action/backport.py
backport-pull-request/poetry.lock
backport-pull-request/pyproject.toml

Fix checkout of target branch in backport action
Ensure that the reference information for the target branch is available and use <remote>/<target-branch> syntax for the checkout command.
Checking out non default branches without remote syntax doesn't work.
https://github.com/greenbone/pipeline-experiments/actions/runs/4111519803/jobs/7095364355

Backport checkout fix

---

README.md
check-version/action.yaml
lint-python/action.yaml

Extract checking the version information of a project form the lint-python action into an own action.
Checking the version information isn't coupled to a linting run, is independent of Python projects and isn't required to run for each linted Python version. Therefore it is moved into an own separate action.
DEVOPS-579

Change: Extract checking version into an own action

---

check-version/action.yaml

Fix activating the python venv for check-version action
It's broken
DEVOPS-579

Fix: Fix activating the python venv for check-version action

---

release/action.yaml

Fix: Always disable admin bypassing #394
Even if the worfklow fails.
when workflow fails is should be disabled anyways

Fix: Always disable admin bypassing

---

poetry/action.yaml

Add more inputs to make the poetry action more flexible. Namely:
* `working-directory` - a path where to run poetry install
* `no-root` - don't install the project itself (mostly for testing purposes)
* `without-dev` - don't install development dependencies
Working directory will be required for the conversion of the docker based Python actions.

Poetry action improvements

---

README.md
release/README.md
release/action.yaml
set-github-user/action.yaml

* Add `release-action` input argument to release action
* If set, it will overwrite the `release-type` argument and the given version will be released, if it is valid (e.g. SemVer or PEP440)
* I have moved the github user setup into a separat action, since these are steps I always need to look up at some weird places (guessing in which action I may have used it)
* Improved readability and refactored the action
* We need to be able to set the version explicit in some situations.
DEVOPS-599

Add: release-version input to release action

---

trigger-workflow/action.yml

Enable input arguments to pass to the workflow, in trigger-workflow action.
We need them.
DEVOPS-614

Add: input arguments to pass to the workflow, in trigger-workflow action

---

poetry/action.yaml

Cache dependencies when using the poetry action by default.
Allow for faster setups by default.
DEVOPS-618

Change: Enable Python dependencies caching for poetry by default

---

poetry/action.yaml

Try to fix poetry caching with setup-python
It seems that setup-python handles changing the current python version according to the desired setup (https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts#L61-L62). Therefore install poetry into the system python before setup-python is called if poetry caching is used.
DEVOPS-618

Change: Try to fix poetry caching with setup-python

---

poetry/action.yaml

Make poetry caching opt-in instead of opt-out
It seems enabling poetry caching creates a lot of issues. Therefore make it optional and opt-in.
DEVOPS-618

Change: Make poetry caching opt-in instead of opt-out

---

dependency-review/action.yml

Add one more allowed license BSD-2-Clause AND BSD-3-Clause 
Due to error: dependency review detected incompatible licenses 
[DEVOPS-624](https://jira.greenbone.net/browse/DEVOPS-624)
[License in Software Products](https://confluence.greenbone.net/display/IQMS/License+in+Software+Products)
[dependency-review](https://github.com/actions/dependency-review-action)

Add more license due to error

---

download-artifact/action/artifact.py

Print settings and absolute paths.
Allow for easier debugging of download artifact action
https://github.com/greenbone/feed-deployment-pipeline/actions/runs/4607173729/jobs/8141748140

Change: Allow for easier debugging of download artifact action

---

download-artifact/action/artifact.py

Make repository argument for download-artifact optional
When using actions and action arguments optional python arguments must allow `--foo` with no additional value.
https://github.com/greenbone/vulnerability-tests/actions/runs/4614487072/jobs/8159510983

Fix: Make repository argument for download-artifact optional

---

admin-bypass/action.yaml

Don't run apt-get install on runners
It seems that this command fails and breaks the action. Also it should not be necessary because wget is already installed and venv should be available after setup-python is run.
https://github.com/greenbone/troubadix/actions/runs/4677351555/jobs/8287964525

Fix: Don't run apt-get install on runners

---

coverage-python/action.yaml

Don't install codecov python package
The package is deprecated and removed from PyPI yesterday. Also installing it seems to be a leftover in our action.
https://about.codecov.io/blog/message-regarding-the-pypi-package/

Fix: Don't install codecov python package

---

dependency-review/action.yml

Allow additional licenses when checking dependencies
Allow MPL-2.0 and (Apache-2.0 AND BSD-3-Clause) OR (Apache-2.0 AND MIT).
Also auto format yaml.
Using the Python packages certifi and sniffio requires additional allowed licenses. Both licenses (or license combinations) are valid.
https://github.com/greenbone/actions/actions/runs/4687322904/jobs/8306475933?pr=497

Add: Allow additional licenses when checking dependencies

---

dependency-review/action.yml

Remove trailing comma in allowed licenses list
Fix checking for licenses
https://github.com/greenbone/actions/actions/runs/4687322904/jobs/8307120628

Fix: Remove trailing comma in allowed licenses list

---

conventional-commits/action.yml
conventional-commits/action/commits.py

Allow to run conventional commits check in workspace
The action itself must be run from the action path as working directory to use the correct virtual environment. To check the desired project for conventional commits a working directory argument is added.
DEVOPS-602

Fix: Allow to run conventional commits check in workspace

---

conventional-commits/action/commits.py

event_path must be a Path in conventional commit action
GitHubEvent class expects a Path instance.
DEVOPS-602

Fix: event_path must be a Path in conventional commit action

---

conventional-commits/action/commits.py

Use base ref with remote name
For creating the git log of the changes in a pull request the git ref must be used with the remote name because it isn't checked out.
DEVOPS-602

Fix: Use base ref with remote name

---

.github/workflows/test-python.yml
coverage-python/action.yaml
lint-python/action.yaml
poetry/action.yaml

Allow to disable installing dependencies via poetry
Sometime we just want to have poetry available and not to install the project dependencies. Therefore make the installation step optional.

Change: Allow to disable installing dependencies via poetry

---

sbom-upload/README.md
sbom-upload/action.yml

Implementing SPDX to Dependency Graph Action.
Improve security posture via the Github Enterprise Advanced Security action to makes it easy to upload an SPDX 2.2 formatted SBOM to GitHub's dependency submission API.
This lets you quickly receive Dependabot alerts for package manifests which GitHub doesn't directly support like pnpm or Paket by using existing off-the-shelf SBOM generators.
Related to Jira [DEVOPS-622](https://jira.greenbone.net/browse/DEVOPS-622)
More info [spdx-dependency-submission-action](https://github.com/marketplace/actions/spdx-dependency-submission-action)

Added action SPDX to dependency graph

---

pypi-upload/README.md
pypi-upload/action.yaml

Add an action to upload Python packages to PyPI
Provide an action for PyPI uploads using poetry to replace workflows using twine at the end.
DEVOPS-633

Add: Add an action to upload Python packages to PyPI

---

reference-version/action.yaml

Raise a warning if reference-version action is used
Mark reference-version as deprecated. With `${{ github.ref_name }}` a better alternative exists.
DEVOPS-535

Change: Raise a warning if reference-version action is used

---

release/action.yaml

Allow to set a release-series for releases via pontos
Requires https://github.com/greenbone/pontos/pull/735 to be released.
Support creating releases for older branches.

Add: Allow to set a release-series for releases via pontos

---

dependency-review/action.yml

Added license MIT/Apache-2.0 to the 
License naming scheme is not unified so this variant must be added otherwise an error is raised.

Added license MIT/Apache-2.0

---

.github/workflows/test-hashsums.yml
.github/workflows/test-python.yml
.github/workflows/test-signature.yml

Always run testing workflows
Allow to require successfully running workflows by always running them.
There is only one additional not satisfying work around for the problem https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Change: Always run testing workflows

---

release/action.yaml

Allow to deactivate creating release file signatures
Add an explicit input variable for deactivating the creation and upload of release file signatures.
DEVOPS-628

Change: Allow to deactivate creating release file signatures

---

.github/workflows/conventional-commits.yml
conventional-commits/README.md
conventional-commits/action/commits.py

Add a link to using conventional commits docs
When creating a PR comment if no conventional commits are found add a link to the usage docs for conventional commits at Greenbone.
DEVOPS-654

Add: Add a link to using conventional commits docs

---

release/action.yaml

Only checkout repo during release if there is no checkout
Avoid running the checkout twice during a release. When using release within a workflow or another action that requires a previous checkout avoid overriding the code by running checkout again.
Required for creating a release for the actions repo.

Change: Only checkout repo during release if there is no checkout

---

.github/workflows/release-action.yml

Use the release action to create releases
Update the release workflow to create GitHub releases via our own release action.

Change: Use the release action to create releases

---

release/action.yaml
sign-release-files/action.yml

Extract signing release files into an own action
Allow to sign release files (and upload the signatures) independently from creating the release. There is a use case were additional files should be added to the release at GitHub and these files should get signatures too.
DEVOPS-628

Change: Extract signing release files into an own action

---

admin-bypass/action.yaml
check-version/action.yaml
lock-branch/action.yaml
setup-pontos/README.md
setup-pontos/action.yml
sign-release-files/action.yml

Add a new action to setup Python and pontos in a virtualenv
We have several actions and workflows that use the latest release of pontos under the hood. Therefore unify the setup and installation of pontos in a single action. This allows reusing the virtual environment and caching. Therefore it will result in faster action runs.
DEVOPS-664

Add: Add a new action to setup Python and pontos in a virtualenv

---

backport-pull-request/action.yml
conventional-commits/action.yml
coverage-python/action.yaml
download-artifact/action.yml
helm-version-upgrade/action.yml
lint-python/action.yaml
mypy-python/action.yaml
poetry/action.yaml
trigger-workflow/action.yml
update-header/action.yaml

Always use Python 3.10 as default
We should use an up to date Python version for all our actions as default.

Change: Always use Python 3.10 as default

---

reference-version/action.yaml

Don't use ${{}} in message text because it gets escaped
Fix printing the deprecation message of reference-version. Only show the variable name here without the full GitHub Actions variable syntax. Otherwise it will be replaced with the content of the variable.

Fix: Don't use ${{}} in message text because it gets escaped

---

release/action.yaml

Don't set gpg key in release action
The gpg key is not used in the release action (at least at the moment). The gpg key is only used in the sign-release-files action.
This fixes the release when files should be signed because importing a gpg key twice results in a gpg error.

Fix: Don't set gpg key in release action

---

setup-pontos/action.yml

Include python version in cache key for setup-pontos
The id on setup-python action to allow getting the installed python version afterwards to include it in the cache key

Fix: Include python version in cache key for setup-pontos

---

mattermost-notify/action.yml
release/action.yaml

Adjust cache key for release and mattermost-notify virtualenvs
Sadly github.action evaluates to the same string in all our actions due to our single actions repo usage. Therefore set a distinct key for the release and mattermost-notify Python virtual environments in the cache.

Fix: Adjust cache key for release and mattermost-notify virtualenvs

---

release/action.yaml

Add version outputs for release action
Allow to get the versions determined and used by the release action via action outputs.
This will allow to actually split a release workflow into several steps.
Requires https://github.com/greenbone/pontos/pull/770

Add: Add version outputs for release action

---

release/action.yaml

Add deprecation messages for release input arguments
Show deprecation messages when strategy and conventional-commits inputs of the release action are used to make users aware of the changes.

Add: Add deprecation messages for release input arguments

---

.github/dependabot.yml

Update dependabot config to create commits which use conventional commit messages.
Include dependency updates in release changelogs
DEVOPS-669

Add: Include dependency updates in release changelogs

---

.github/dependabot.yml

Drop include: "scope" from dependabot for testing purposes
Currently it isn't obvious what the setting is doing actually. Therefore remove it for testing purposes.
DEVOPS-669

Drop `include: "scope"` from dependabot for testing purposes

---

backport-pull-request/tests/test_config.py

Avoid code scanning warning
Remove unused local variables to resolve code scanning warnings in backport pull request action tests.
https://github.com/greenbone/actions/security/code-scanning/1

Avoid code scanning warning

---

backport-pull-request/poetry.lock
conventional-commits/poetry.lock
download-artifact/poetry.lock
trigger-workflow/poetry.lock

Update dependencies of Python based actions
Update to newest releases of the dependencies for our Python based actions. This also allows for supporting the new dependencies category for our convention commits action.

Change: Update dependencies of Python based actions

---

backport-pull-request/action.yml
conventional-commits/action.yml
download-artifact/action.yml
mypy-python/action.yaml
trigger-workflow/action.yml

Use v2 actions in main
When using our own action in a composite action always use the v2 version in the main branch too. This prepares for a possible switch from a v2 branch to a v2 tag.
DEVOPS-679

Change: Use v2 actions in main

---

.github/workflows/codeql.yml
.github/workflows/conventional-commits.yml
.github/workflows/dependency-review.yml
.github/workflows/sbom-upload.yml
.github/workflows/test-doc-coverage.yml
.github/workflows/test-download-artifacts.yml
.github/workflows/test-hashsums.yml
.github/workflows/test-python.yml
.github/workflows/test-release.yml
.github/workflows/test-signature.yml
.github/workflows/test-trigger-workflow.yml
.github/workflows/unittests.yml

Cleanup all workflows
Use consistent specification of events, used branches and tags. Use GITHUB_OUTPUT instead of GITHUB_ENV where applicable. Using the env pollutes the environment of **all** following steps. Therefore it should only be used for setting required environment variables.

Change: Cleanup all workflows

---

mypy-python/action.yaml

Don't require packages input for mypy action
packages input argument is deprecated and therefore not required anymore.

Fix: Don't require packages input for mypy action

---

dependency-review/action.yml

Allow MIT AND Python-2.0 as valid license
Allow MIT and Python-2.0 as allowed licenses for using the [exceptiongroup](https://github.com/agronholm/exceptiongroup) backport as a (sub-)dependency. It got required with the latest anyio update. See for example https://github.com/greenbone/pontos/actions/runs/5119229445
For example:
https://github.com/greenbone/pontos/actions/runs/5119229445
https://github.com/greenbone/pontos/pull/784

Add: Allow MIT AND Python-2.0 as valid license

---

is-latest-tag/README.md
is-latest-tag/action.yml
release-type/README.md
release-type/action.yml

Add new actions release-type and is-latest-tag
Add two new actions for supporting creating releases. release-type determines the release type from PR labels or input. is-latest-tag checks if a new tag is the latest tag.
https://github.com/greenbone/gvmd/pull/2005

Add: Add new actions release-type and is-latest-tag

---

is-latest-tag/action.yml

Fix is-latest-tag EOF usage
EOF needs to be directly at the start of the line and must not be indented.
https://github.com/greenbone/gvmd/actions/runs/5208881814/jobs/9398012007?pr=2005

Fix: Fix is-latest-tag EOF usage

---

is-latest-tag/README.md

Improve README of is-latest-tag
Use string comparison for checking the output of is-latest-tag because GitHub actions don't really have booleans.

Change: Improve README of is-latest-tag

---

sbom-upload/action.yml

Use a known-good release of `sbom-tool` to download the binary as a workaround, as binaries for the `latest` release are currently not available (see https://github.com/microsoft/sbom-tool/issues/271 ).

Fix failing download of sbom-tool

---

dependency-review/action.yml

Add 0BSD (BSD Zero Clause License) to action.yml
The license is compatible with our useage and came up as "not allowed" in the dependency review. According to internal documentation, 0BSD should have been allowed already.
https://github.com/greenbone/scan-management-frontend/actions/runs/5245115892/jobs/9472098011?pr=700

Allow 0BSD license

---

checkout/action.yml

Fix setting the ref output for checkout action
The output was missing and getting the ref was broken for detached heads. In case of detached heads we don't have a ref.
https://github.com/greenbone/notus-data/actions/runs/5266056102?pr=62

Fix: Fix setting the ref output for checkout action

---

release/action.yaml
sign-release-files/action.yml

Fix and improve release without signing
It seems the signing is always run at the moment despite setting `sign-release-files` to a value other then "true".
https://github.com/greenbone/gsa/actions/runs/5421140342/jobs/9856197131

Improve check for signing action

---

admin-bypass/action.yaml
lock-branch/action.yaml

Run enforce-admins and lock-branch from pontos package
Requires https://github.com/greenbone/pontos/releases/tag/v23.7.0
All GitHub scripts are provided with the latest pontos package. Therefore there is no need in downloading them from the repo anymore.

Change: Run enforce-admins and lock-branch from pontos package

---

conventional-commits/README.md
conventional-commits/action.yml

Allow to specify refs for conventional commits action
Allow to adjust the refs for gathering the changes. This is mostly interesting for testing at the moment.
DEVOPS-720

Add: Allow to specify refs for conventional commits action

---

set-github-user/README.md
set-github-user/action.yaml

Use github-actions user as default for set-github-user
Make all inputs optional by just using the github-actions user as default for the git credentials. Allow the action to be used without any input arguments.

Change: Use github-actions user as default for set-github-user

---

conventional-commits/action.yml

Fix fetching commits for conventional commits action
The remote was missing from the fetch statement.
https://github.com/greenbone/pipeline-experiments/actions/runs/5484263979/jobs/9991588937?pr=91

Fix fetching commits for conventional commits action

---

lint-python/action.yaml

Fix: Ignore version input
Don't forward version input anymore. This resulted in workflow warnings because the deprecation message is raised already if the input is set. Not only if it has a value.
For example https://github.com/greenbone/autohooks-plugin-mypy/actions/runs/5486147206

Fix: Ignore version input

---

coverage-python/action.yaml
mypy-python/action.yaml

Ignore version input for coverage-python action
Avoid workflow warning when using the action. A deprecation warning is already raised if the input is set and not only if a value is set.

Change: Ignore version input for coverage-python action

---

conventional-commits/action/commits.py

Print GitHub doc URL if available in conventional commits
Improved error message with details on GitHub. Would be nice to move this also into pontos.

Add: Print GitHub doc URL if available in conventional commits

---

dependency-review/action.yml

Fix: Remove "MIT/Apache-2.0" from allowed licenses again
Not valid license ...
Licenses only work with "AND" or "OR" ... not with `/` ...

Fix: Remove "MIT/Apache-2.0" from allowed licenses again

---

dependency-review/action.yml

Fix dependency review action and remove trailing comma
Remove trailing comma at end of allowed licenses. Currently it just always fails.

Fix dependency review action and remove trailing comma

---

container-build-push-3rd-gen/action.yaml
container-build-push-docker/action.yaml
container-build-push-generic/action.yaml
container-build-push-ghcr/action.yaml

Remove input types from container build actions
There is no input type parameter for actions. It's always string by the way.

Remove input types from container build actions

---

doc-coverage-clang/action.yml
update-header/action.yaml

Use actions/checkout@v3 for doc-coverage-clang and update-header
v3 of this action got released long time ago.

Deps: Use actions/checkout@v3 for doc-coverage-clang and update-header

---

.github/workflows/release-action.yml

Use release action from main for releasing the actions
This will allow to use changes for the release action in main without having to create a release before. Without the change we need to create an actions release with the old version of the release action to be able to use the new version of the release on the nextnext release. Confused? Therefore this change should be applied.

Change: Use release action from main for releasing the actions

---

conventional-commits/README.md
conventional-commits/action.yml

Try to fix conventional commits for outdated PR branches
github.event.pull_request.base.sha always points to the latest commit in the target branch. If the target branch and the PR branch diverge git log can't create a "simple" log without having more commits. It requires to find common ancestors. Therefore fetch the full history for now and checkout branch refs instead of the commits.
To be able to only fetch commits required to create the desired log we would need to know the commit ID of the first commit in the PR branch.

Try to fix conventional commits for outdated PR branches

---

conventional-commits/action.yml

Fix creating log for conventional commits
For the log it is required to specify the refs with the used remote.

Fix creating log for conventional commits

---

pipx/README.md
pipx/action.yml

Add new action for using pipx
Allow to install Python applications with pipx. pipx seems to be a lot faster then pip and it automatically creates a virtual environment that can be cached.
Currently caching is disabled by default because it doesn't bring much advantage.
DEVOPS-763

Add new action for using pipx

---

pipx/action.yml

Allow to pass a python installation to be used by the pipx action
Setting up a python version via the setup-python action before calling the pipx actions allows for more flexible setup. Otherwise all inputs of setup-python must have been passed through the pipx action too.

Allow to pass a python installation to be used by the pipx action

---

poetry/README.md
poetry/action.yaml

Simplify poetry action by using pipx action
Use pipx action to install poetry. Using the pipx action simplifies the venv and cache handling a lot while still keeping all functionality.
DEVOPS-763
Requires self hosted runner having pipx installed.

Change: Simplify poetry action by using pipx action

---

admin-bypass/action.yaml
check-version/action.yaml
pipx/README.md
pipx/action.yml
release/action.yaml
setup-pontos/README.md
setup-pontos/action.yml
sign-release-files/action.yml

Refactor setup-pontos to use pipx action
Using the new pipx action heavily simplifies setup-pontos. pipx creates a virtual python environment automatically. The setup-pontos action ensures that pontos is installed only once now too.
DEVOPS-763
Requires self hosted runner having pipx installed.

Change: Refactor setup-pontos to use pipx action

---

conventional-commits/README.md
conventional-commits/action.yml

Fix conventional commits for forked PRs again.
`github.base_ref` contains the branch name in the forked repository. Therefore it can't be used to reference a commit in forked PRs.
https://github.com/greenbone/gsa/actions/runs/5631494476

Conventional commits

---

conventional-commits/action.yml
release/action.yaml

Fix the next release
We need a new setup-pontos v3 version before we can run pontos-release without sourcing the venv. Therefore source the venv again for the next release.
https://github.com/greenbone/actions/actions/runs/5643232133/job/15284634964

Fix the release

---

pipx/action.yml

Support pipx < 1.1.0
Only pipx 1.1.0 got the pip environment command. Sadly this version is not available in Ubuntu 20.04 and 22.04 and therefore not on our self hosted runners.

Fix: Support pipx < 1.1.0

---

mattermost-notify/action.yml

Fix highlighting users with mattermost-notify
The `--highlight` argument accepts one or more values. Therefore it must be passed after the positionals for the url and channel. Otherwise the values for urls and channels would be considered as additional users to be highlighted.

Fix highlighting users with mattermost-notify

---

mattermost-notify/README.md
mattermost-notify/action.yml

Adjust mattermost-notify action to use sane defaults for all use cases
It wont be used for workflow_run events as main use case anymore. Therefore use defaults that fit for all kind of events.

Mattermost notify defaults

---

mattermost-notify/action.yml

Quote input arguments for mattermost-notify
The input argument values may contain spaces and then they are considered as the next argument instead of value. Therefore quote all input argument values. This will ensure that they are parsed as argument values.

Fix: Quote input arguments for mattermost-notify

---

.github/dependabot.yml
backport-pull-request/poetry.lock
conventional-commits/poetry.lock
download-artifact/poetry.lock
helm-version-upgrade/poetry.lock
trigger-workflow/poetry.lock

Update deps of Python based actions for cffi security update
It seems that dependabot couldn't create PRs for updating the dependencies anymore. Therefore update all dependencies manually to fix a security issue in the cffi package.

Deps: Update deps of Python based actions for cffi security update

---

coverage-python/README.md
coverage-python/action.yaml

Disable caching of poetry in coverage-python action
The caching is currently broken and therefore should be deactivated.
https://github.com/greenbone/autohooks-plugin-pylint/actions/runs/5710696688/job/15667895141#step:11:32

Fix: Disable caching of poetry in coverage-python action

---

mattermost-notify/action.yml

Fix: highlight in mattermost-notify
The mattermost-notify service needs highlights as single arguments.
None

Fix: highlight in mattermost-notify

---

release/README.md
release/action.yaml

Add new arguments for release workflow
* next-version - to set an explicit version after a release or to completely deactivate a version update after a release
* github-pre-release - to enforce uploading a release as a pre-release to GitHub
Support new release workflows.
DEVOPS-828
DEVOPS-826

New release options

---

release/action.yaml

Use correct input variable to enforce creating a GitHub pre-release
The input variable is named github-pre-release and not pre-release.
DEVOPS-826

Fix: Use correct input variable to enforce creating a GitHub pre-release

---

container-build-push-generic/action.yaml

Change: keep previous PR comments from SBOM scan in container-build-push-generic
Since we have several images in some repositoies, we have to keep all the comments, otherwise they will be replaced
None

Change: keep previous PR comments from SBOM scan in container-build-push-generic

---

dependency-review/action.yml

Allow Apache-2.0 AND BSD-3-Clause AND MIT AND OFL-1.1
Used by [pheme](https://github.com/greenbone/pheme) dependency [fonttools](https://github.com/fonttools/fonttools).
Marked as an incompatible license: https://github.com/greenbone/pheme/actions/runs/6611060691

Add: Allow Apache-2.0 AND BSD-3-Clause AND MIT AND OFL-1.1

---

test-node/action.yaml

Remove build step from test-node action
Testing npm projects do not require them to be build beforehand. The node test-frameworks build the code itself.

Change: Remove build step from test-node action

---

pipx/action.yml

Use `--value` instead of `-v` for getting the pipx environment vars
PR https://github.com/pypa/pipx/pull/1159 did break the CLI and changed the `-v` argument to upper letter `-V`

Fix: Use `--value` instead of `-v` for getting the pipx environment vars

---

.github/workflows/test-signature.yml
signature/action.yml

Put gpg fingerprint in vars and allow for password with special characters like `$`
The gpg fingerprint of the signature action testing key doesn't need to be a secret.
Creating signatures shouldn't fail with special characters in user input.
DEVOPS-903

Put gpg fingerprint in vars

---

is-latest-tag/action.yml

Not sure what the previous check was about. Now it is the latest version
1. if the major version is greater
2. if the major versions are equal and the minor version is greater
3. if the major and minor versions are equal and if the patch version is
greater
It didn't consider the 23.0.0 release of GSA as latest tag.

Fix is latest tag

---

is-latest-tag/action.yml

Fix typo in if-condition
Failing CI checks:
```
Run greenbone/actions/is-latest-tag@v3
Run if [ "branch" = "tag" ]; then
/home/runner/work/_temp/b7cf2293-d120-457c-be78-971c55f23833.sh: line 20: syntax error near unexpected token `elif'
Error: Process completed with exit code 2.
```

Fix: Fix typo in if-condition

---

update-header/action.yaml

Rename set-git-user to set-github-user
DEVOPS-765
DEVOPS-765

Rename set-git-user to set-github-user

---

pypi-upload/README.md
pypi-upload/action.yaml

Support trusted publishing via OICD on PyPI
Use pypa/gh-action-pypi-publish action to upload packages to PyPI which uses trusted publishing via OpenID Connect (OICD) when not passing a token as password.
DEVOPS-931

Change: Support trusted publishing via OICD on PyPI

---

pipx/action.yml
pypi-upload/action.yaml

Update actions/setup-python and actions/cache to the latest major releases.
Fix deprecation warning `Node.js 16 actions are deprecated`
https://github.com/greenbone/actions/actions/runs/7654546686

Setup python v5

---

check-version/action.yaml
checkout/action.yml
dependency-review/action.yml
doc-coverage-clang/action.yml
helm-build-push/README.md
helm-version-upgrade/README.md
install-node/action.yaml
is-latest-tag/README.md
lint-golang/action.yml
pypi-upload/action.yaml
sbom-upload/action.yml
sign-release-files/action.yml

Update actions/checkout v3 to v4
Avoid the `Node.js 16 actions are deprecated` warning.
https://github.com/greenbone/autohooks/actions/runs/7665538693

Change: Update actions/checkout v3 to v4

---

dependency-review/action.yml

Adds the attribution only license:
- https://opensource.org/license/bsl-1-0/
This required for openvasd tls functionality:
https://github.com/greenbone/openvas-scanner/blob/openvasd-hyper-hyper/rust/Cargo.lock#L2754

Add: BSL-1.0

---

sign-release-files/README.md
sign-release-files/action.yml

Allow to set a repository for signing release files to fix signing releases files outside of greenbone
Make the signing of release assets more flexible and don't pin it to the greenbone organization. Currently only repos within the greenbone organization can be used.
By default the github.repository (the repo of the running workflow) is used.

Add: Allow to set a repository for signing release files

---

release/README.md
release/action.yaml

Allow to pass a specific repository to be released
Currently it's not possible to create a release for a repository outside of the greenbone GitHub organization. With this change the current repo will be released which is not required to be a repo of the greenbone GitHub organization anymore.

Release update

---

container-build-push-generic/README.md
container-build-push-generic/action.yaml

Change: image-url default to github.repository
It is mostly the default in every repository.
None

Change: image-url default to github.repository in container-build-push-generic action

---

download-artifact/README.md
download-artifact/action.yml

This PR fixes the default of `path` of the download-artifact Action.
Using `.` as the default path is expected to refer to the current working directory. Currently however, it seems to refer to `.`, relative to the directory of the Action itself, see https://github.com/greenbone/notus-generator/actions/runs/7887096945/job/21521596772:
```
Run greenbone/actions/download-artifact@v3
with:
[...]
path: .
Extracting artifact '[redacted]' to '/home/runner/work/_actions/greenbone/actions/v3/download-artifact'.
Downloading artifacts completed successfully ✅.
Run ls -la
total 8
drwxr-xr-x 2 runner docker 4096 Feb 13 13:16 .
drwxr-xr-x 3 runner docker 4096 Feb 13 13:16 ..
```
Note that I haven't actually tested this change.
Stumbled upon this while working on …

Fix: Default path of download-artifact Action

---

mattermost-notify/action.yml

Added "Markdown formatted message" as input parameter for notify-action
The program can use both, a free text message or a success notification with the existing inputs.
DEVOPS-956
[Mattermost-notify](https://github.com/greenbone/mattermost-notify/blob/main/mattermost_notify/parser.py)

Add: Markdown formatted message as input parameter for notify-action

---

mattermost-notify/README.md
mattermost-notify/action.yml

This PR fixes the mattermost-notify Action / https://github.com/greenbone/actions/pull/997.
- Using `:` in an unquoted string makes YAML sad
- `inputs.free` doesn't exist, so I assume `inputs.message` is actually meant
Tested in https://github.com/greenbone/notus-generator/actions/runs/7901348733/job/21564795251 as part of https://github.com/greenbone/notus-generator/pull/970.

Fix: mattermost-notify Action

---

mattermost-notify/action.yml

This PR fixes escaping of strings in the mattermost-notify Action.
Currently it's really hard to use a message when it is the output of another application.
As a user I don't want to take care of the escaping needed (e.g. when the message contains special characters interpreted by Bash), but just want to get my message sent.
Tested in https://github.com/greenbone/notus-generator/actions/runs/7987120546/job/21808941466?pr=970#step:5:332.
Noticed during https://github.com/greenbone/notus-generator/pull/970.

Fix: Escaping in mattermost-notify Action

---

oci-info/action.yml

Add: multi line output support
The get-tags command returns a new line list.
None

Add: multi line output support in oci-info

---

.github/workflows/test-is-latest-tag.yml
is-latest-tag/README.md
is-latest-tag/action.yml

Make is-latest-tag action more flexible
Allow to run the action not only for pushed tag events. With this change it will be possible to run it even for workflow_dispatch events.

Make is-latest-tag action more flexible

---

release-type/action.yml

Support setting "calendar release" label for release type calendar
Cloud uses this label for creating calendar releases. Therefore the release-type action should support it too.

Add: Support setting "calendar release" label for release type calendar

---

oci-info/action/oci.py

Fix: oci info auth
OCI authentication is only allowed to exist within the HTTP context of the token request. Therefore, now the authentication context is explicitly set for the token request.
None

Fix: oci info auth

---

pr-conventional-commit-labeler/action/labels.py

To prevent a crash when trying to set empty labels on a PR `labels`
should be checked before transmitting to github.

Fix: pr-conventional-commit-labeler: crash on empty labels set

---

dependency-review/action.yml

Allow `Apache-2.0 AND MIT AND NOASSERTION` as license combination
This license combination is detected for lxml-stub a Python package that contains typings for lxml.
https://github.com/greenbone/python-gvm/pull/1127#issuecomment-2014454683

Allow `Apache-2.0 AND MIT AND NOASSERTION` as license combination

---

dependency-review/action.yml

This reverts commit 8a03b95ddc59ca2520bc2dd154f32d9f412cd8c9.
Despite being displayed as the license to add `Apache-2.0 AND MIT AND NOASSERTION` seems to be not a valid license combination and now causes errors on every dependency check.

Revert "Allow `Apache-2.0 AND MIT AND NOASSERTION` as license combination

---

dependency-review/action.yml

Add: Allow LGPL-2.0-only AND LGPL-2.1-or-later as license combination
```
The following dependencies have incompatible licenses:
poetry.lock » astroid@3.2.2 – License: LGPL-2.0-only AND LGPL-2.1-or-later
Error: Dependency review detected incompatible licenses. 
```

Add: Allow LGPL-2.0-only AND LGPL-2.1-or-later as license combination

---

container-build-push-generic/action.yaml

Change: Disable docker load function in multi arch builds
The docker --load function does not support multi platform builds. So we need to disable them on this build mode.
https://github.com/docker/buildx/issues/59
DEVOPS-1069

Change: Disable docker load function in multi arch builds

---

container-build-push-generic/README.md
container-build-push-generic/action.yaml

Change: Make qemu local static binaries and buildx-container optional.
The docker daemon has now build in multi platform build support as long as the qemu files are installed.
DEVOPS-1079

Change: Make qemu local static binaries and buildx-container optional.

---

container-build-push-generic/README.md
container-build-push-generic/action.yaml

Add: Tag output in container-build-push-generic action
Add: Output for annotations and labels
DEVOPS-1082
DEVOPS-1082

Add: annotations,  labels and tags output in container-build-push-generic action

---

container-multi-arch-manifest/README.md
container-multi-arch-manifest/action.yaml

Change: use docker buildx imagetools in manifest action
Add: cosign support
This should allow us to use the manifest list checksum to verify multi arch images.
DEVOPS-1082
DEVOPS-1082

Change: use docker buildx imagetools in manifest action

---

dependency-review/README.md

Add permissions to write to PR to the dependency review example.
Using dependency review action without permission `pull-requests: write` issues a warning: `Warning: Unable to write summary to pull-request. Make sure you are giving this workflow the permission 'pull-requests: write'. `
[Pipeline run with warning](https://github.com/greenbone/opensight-notification-service/actions/runs/9933940161/job/27437506097?pr=25#step:2:157)

fix dependency review readme: add permissions to write to PR

---

doc-coverage-clang/action.yml

This adds the Codecov token to the doc-coverage-clang action, which is now required when not using fork repos for pull requests. Also, the flag "documentation" is added so the documentation coverage can be separated from other types like unit test coverage later.

Add: Codecov token and flag for doc-coverage-clang

---

container-multi-arch-manifest/action.yaml

Change: newline separator for tags pass to cosign action
We need a newline separator here for the cosign action
DEVOPS-1135

Change: newline separator for tags pass to cosign action

---

dependency-review/action.yml

- Allow the 'LGPL-3.0-or-later' license in the dependency review action
We had a dependency that uses the 'LGPL-3.0-or-later' license. It was verified to be allowed, and is therefore added in this PR.
Please check the list of allowed licenses.
T5-1074
- [N/A] Tests

Add: Allow 'LGPL-3.0-or-later' license

---

pipx/action.yml

Fix: pipx action don't set --python arg if no other python version is installed
DEVOPS-1272
DEVOPS-1272
In pipeline tested

Fix: pipx action don't set --python arg if no other python version is installed

---

oci-info/action.yml

Change: " to ' for input vars in oci-info action.yml
A common mistake is using double quotes (") instead of single quotes (') for input arguments. Bash handles $ and other special characters correctly when they are enclosed in single quotes (') rather than double quotes (").
None

Change: " to ' for input vars in oci-info action.yml

---

mattermost-notify/README.md
mattermost-notify/action.yml

This PR allows use of the `--short` flag to trigger short format messages for git status updates.
The flag could not be controlled via the action yet.
Ref.: [DEVOPS-1269](https://jira.greenbone.net/browse/DEVOPS-1269)

Allow use of short format status updates

---

mattermost-notify/action.yml

This PR pins the pip package version )that is being installed during each run) to the current stable version.
Currently the action is always using the last published package on PyPi. Pinning the is needed so changes to the code can be made, without switching everyone over to the new version immidiatly.
Ticket: [DEVOPS-1269](https://jira.greenbone.net/browse/DEVOPS-1269)

Pin mattermost-notify

---

pypi-upload/action.yaml

Change: use pypa/gh-action-pypi-publish v1.11.0
It looks like the current v1 does not work in our setup anymore
None

Change: use pypa/gh-action-pypi-publish v1.11.0

---

dependency-review/action.yml

Added Unicode-3.0 to permitted license list.
It was needed by a [dependency](https://github.com/greenbone/management-console-connector/actions/runs/12142055483?pr=49).
LEG-206

Add: Unicode-3.0

---

dependency-review/action.yml

Sort licenses alphabetically in dependency review workflow.
The workflow fails with: 'Error: Invalid license(s) in allow-licenses: Unicode-3.0'

Change: Sort licenses alphabetically in dependency review workflow

---

dependency-review/action.yml

Removed Unicode-3.0.
Not supported by [dependency-review-action](https://github.com/actions/dependency-review-action/pull/855)
https://github.com/actions/dependency-review-action/pull/855

Change: Remove Unicode-3.0 as it is not supported upstream

---

dependency-review/action.yml

Allow MIT-CMU
Needed by [pillow](https://github.com/python-pillow/Pillow), a dependency of pheme. Was flagged by Dependency review in https://github.com/greenbone/pheme/pull/941.
Was already approved before (See ticket below) but missing in the white list.
LEG-197

Add: Allow MIT-CMU

---

poetry/action.yaml

set default poetry version to 1.8.0
2.0.0 seems to break a major number of our workflows.
DEVOPS-1372

Fix: (Temp) set default poetry version to 1.8.0

---

conventional-commits/action.yml

Use poetry 1.8.0 temporary until 2.0.0 is bug-free
https://github.com/python-poetry/poetry/issues/9961

Fix: (Temp) Use poetry 1.8.0 temporary until 2.0.0 is bug-free

---

backport-pull-request/README.md
backport-pull-request/action.yml
conventional-commits/README.md
conventional-commits/action.yml
coverage-python/README.md
coverage-python/action.yaml
download-artifact/action.yml
helm-version-upgrade/action.yml
lint-python/README.md
lint-python/action.yaml
mypy-python/README.md
mypy-python/action.yaml
oci-info/README.md
oci-info/action.yml
poetry/README.md
poetry/action.yaml
pr-conventional-commit-labeler/README.md
pr-conventional-commit-labeler/action.yml
trigger-workflow/action.yml

Unpin poetry version, by removing the default again
poetry 2.0.1 fixes our issues
DEVOPS-1374
Reverts #1311 #1314 #1315 
https://github.com/python-poetry/poetry/issues/9961

Remove: Unpin poetry version, by removing the default again

---

install-cgreen/README.md
install-cgreen/action.yml

Add a new reusable action to install cgreen for running tests in our C projects.
cgreen wont be available in current Debian versions via deb packages. Therefore we have to install it manually from source via a release tarball.

Add new action for installing cgreen

---

lint-python/action.yaml

Allow to specify python tool for format checks in lint action
Black has a serious competitor in form of ruff format nowadays. Therefore allow to specify the format checker in the python linting workflow.

Allow to specify python tool for format checks in lint action

---

update-header/action.yaml

update header - add option for single year license format
Default behavior remains unchanged.
Having a single year instead of a year range eases the maintenance and noise in the git diff.  The purpose of the action in this configuration is to spot missing license headers.
Feature introduced in pontos: https://github.com/greenbone/pontos/pull/1021

change: update header - add option for single year license format

---

dependency-review/action.yml

Add ZPL-2.1 to list of allowed licenses in dependency-review action.
The license is allowed and we want to use it.

Add: Add ZPL-2.1 to allowed licenses in dependency-review action

---

pipx/action.yml

Update actions/cache to 4.2.2 to fix error
gvm-tools has an issue with stating an outdated now unsupported actions/cache version is used. Try to fix this issue by updating to the latest release.
For me there seems to be something wrong with our used version. See new commit https://github.com/actions/cache/commit/1bd1e32a3bdc45362d1e726936510720a7c30a57 And old commit https://github.com/actions/cache/commit/1bd1e32a3bdc45362d1e726936510720a7c30a57
gvm-tools CI has an issue
https://github.com/greenbone/gvm-tools/actions/runs/13757012144/job/38465960419?pr=1195

Update actions/cache to 4.2.2 to fix error

---

uv/README.md
uv/action.yml

Add an action to install applications with uv tool
Allow to use uv for installing packages from PyPI. uv is much faster then pipx and may consume less CI minutes.

Add an action to install applications with uv tool

---

release-version/README.md
release-version/action.yml

Add a new action for determining the release version
The action allows to determine the release version before actually making the release. With this change it will possible to split up making the release into:
* determine the release type
* get the release version
* create the release
* sign the release
with possible additional steps in between.

Add a new action for determining the release version

---

release/README.md
release/action.yaml

Add changelog and last-release-version inputs to release action
Allow to pass a path to a changelog file and the last release version to the release action. With this change it will possible to generate a changelog outside of the release action and to use the release-version action beforehand of the release action.
Supports and requires https://github.com/greenbone/pontos/releases/tag/v25.3.0

Add changelog and last-release-version inputs to release action

---

lock-branch/action.yaml
release/action.yaml
setup-pontos/README.md
setup-pontos/action.yml

Deprecated venv outputs of setup-python
How pontos is installed should be an implementation details. Workflows should not rely on the existence of some venv and only on pontos being in the PATH.
https://github.com/greenbone/gsa/actions/runs/13852855211/job/38763241273

Deprecated venv outputs of setup-python

---

.github/workflows/auto-merge.yml
.github/workflows/codeql.yml
.github/workflows/conventional-commits.yml
.github/workflows/dependency-review.yml
.github/workflows/release.yml
.github/workflows/sbom-upload.yml
.github/workflows/test-doc-coverage.yml
.github/workflows/test-download-artifacts-test-workflow.yml
.github/workflows/test-download-artifacts.yml
.github/workflows/test-hashsums.yml
.github/workflows/test-is-latest-tag.yml
.github/workflows/test-python.yml
.github/workflows/test-signature.yml
.github/workflows/test-trigger-workflow-failing-workflow.yml
.github/workflows/test-trigger-workflow-long-running-workflow.yml
.github/workflows/test-trigger-workflow-test-workflow.yml
.github/workflows/test-trigger-workflow.yml
.github/workflows/unittests.yml

Add cancellation of running CI jobs on new commit in same ref
to all workflows.
We usually don't need to continue running old jobs when a new commit comes in that starts the same jobs again.
This saves us some running time and resources.
see DEVOPS-1538
- [NA] Tests

Add: cancellation of running CI jobs on new commit

---

deploy-env/README.md
deploy-env/action.yml
deploy-env/run.yml

[Fix: wrong input description of inventory and inventory-path](https://github.com/greenbone/actions/commit/21f25f7acb197ac9854372839be717d66946b8f3)
[Change: make vars file optional](https://github.com/greenbone/actions/commit/b050d3fb36a61ac8e3954149373eb8ae88e73dd2)
The description of  inventory and inventory-path was mixed.
The vars file can be optional, because all statements like copy, env and cmd are already optional and can be placed in the inventory file.
None

Fix: wrong input description of inventory and inventory-path

---

trigger-harbor-replication/README.md
trigger-harbor-replication/action.yml

Add action to trigger a harbor replication policy
This job is used in some workflows to trigger replicating all uploaded images to our public container registry. It just got extracted into an action to hide implementation details.

Add action to trigger a harbor replication policy

---

create-multi-arch-container-image/action.yml

Show error if creating a multi arch image fails
Display the error of `docker buildx imagetools create` if it fails.

Show error if creating a multi arch image fails

---

container-multi-arch-manifest/action.yaml

Fix: manifest action muti project upload #1465 
On a multi repository upload the docker buildx output containes multible digest's from multible container layers. We have to grep the digest from the last two lines.
- [DEVOPS-1681](https://jira.greenbone.net/browse/DEVOPS-1681)

Fix: manifest action muti project upload

---

generate-dependabot-config/action.yml

Not Skip the CI when commiting on HEAD, so the PR can pass the protection rules.
Change: Don't you skip that CI, sir.
Skipping the CI will skipping the CI on the most recent push (HEAD) and HEAD can not be merged (branch protection).
https://github.com/greenbone/actions/pull/1394
DEVOPS-1551

Change: Don't you skip that CI, sir.
